<?php
use App\Core\View;
?>
<div class="row">
    <!-- Configuration panel -->
    <div class="col-lg-6 mb-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-header bg-white">
                <h5 class="mb-0 fw-semibold text-primary"><i class="fas fa-sliders-h me-2"></i>Global System Parameters</h5>
            </div>
            
            <div class="card-body">
                <form action="<?= BASE_URL ?>/settings/save" method="POST">
                    <?= View::csrfField() ?>

                    <?php foreach ($settings as $set): ?>
                        <div class="mb-3">
                            <label for="<?= View::escape($set['setting_key']) ?>" class="form-label text-capitalize">
                                <?= str_replace('_', ' ', View::escape($set['setting_key'])) ?>
                            </label>
                            
                            <?php if ($set['setting_key'] === 'welfare_fund_balance' || $set['setting_key'] === 'monthly_contribution_fee'): ?>
                                <input type="number" step="0.01" class="form-control" id="<?= View::escape($set['setting_key']) ?>" name="<?= View::escape($set['setting_key']) ?>" required value="<?= View::escape($set['setting_value']) ?>">
                            <?php else: ?>
                                <input type="text" class="form-control" id="<?= View::escape($set['setting_key']) ?>" name="<?= View::escape($set['setting_key']) ?>" required value="<?= View::escape($set['setting_value']) ?>">
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>

                    <button type="submit" class="btn btn-primary w-100 py-2">Save System Settings</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Backup and Restore panel -->
    <div class="col-lg-6 mb-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-header bg-white">
                <h5 class="mb-0 fw-semibold text-danger"><i class="fas fa-database me-2"></i>Database Backup & Recovery</h5>
            </div>
            
            <div class="card-body d-flex flex-column justify-content-around">
                <!-- Backup -->
                <div class="border border-1 rounded p-3 mb-3">
                    <h6 class="fw-semibold text-dark mb-1">Download Database Backup</h6>
                    <p class="text-muted small mb-3">Downloads a complete SQL schema dump file including configuration variables, logs, and users.</p>
                    <a href="<?= BASE_URL ?>/settings/backup" class="btn btn-outline-primary btn-sm px-4">
                        <i class="fas fa-download me-1"></i> Generate SQL Backup
                    </a>
                </div>

                <!-- Restore -->
                <div class="border border-1 rounded p-3">
                    <h6 class="fw-semibold text-danger mb-1">Restore Database from Backup</h6>
                    <p class="text-muted small mb-3">Warning: Restoring will overwrite existing data. Upload a valid <code>.sql</code> backup file generated by AidFlow.</p>
                    
                    <form action="<?= BASE_URL ?>/settings/restore" method="POST" enctype="multipart/form-data">
                        <?= View::csrfField() ?>
                        <div class="mb-3">
                            <input class="form-control form-control-sm" type="file" id="backup_file" name="backup_file" required accept=".sql">
                        </div>
                        <button type="submit" class="btn btn-danger btn-sm px-4" onclick="return confirm('Restore database now? All existing data will be replaced!')">
                            <i class="fas fa-upload me-1"></i> Upload & Restore SQL
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Audit Trail Grid -->
<div class="row">
    <div class="col-12">
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0 fw-semibold"><i class="fas fa-history me-2"></i>Full System Audit Trail</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover align-middle datatable w-100">
                        <thead class="table-light">
                            <tr>
                                <th>Timestamp</th>
                                <th>Actor Username</th>
                                <th>Account Role</th>
                                <th>Action Category</th>
                                <th>Audit Details</th>
                                <th>IP Address</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($audit_logs as $log): ?>
                                <tr>
                                    <td><?= View::formatDateTime($log['created_at']) ?></td>
                                    <td class="fw-semibold"><?= View::escape($log['username'] ?? 'System') ?></td>
                                    <td><span class="badge bg-secondary"><?= View::escape($log['role'] ?? 'System') ?></span></td>
                                    <td><span class="badge bg-primary"><?= View::escape($log['action']) ?></span></td>
                                    <td><?= View::escape($log['details']) ?></td>
                                    <td><code class="small"><?= View::escape($log['ip_address']) ?></code></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
